environment:
  matrix:
  - nodejs_version: 8

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: (new-object net.webclient).DownloadFile('https://github.com/mbuilov/gnumake-windows/raw/master/gnumake-4.2.1-x64.exe', 'C:\projects\google-api-nodejs-client\make.exe')
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

test_script:
  - node --version
  - npm --version
  - npm rebuild
  - npm test

build: off

matrix:
  fast_finish: true
